version: '3.10'

services:
  crypto-pro:
    container_name: crypto-pro
    image: ghcr.io/devind-team/cryptopro-pycades:latest
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 80
    restart: always
    ports:
      - '8095:80'